/*
 * generated by Xtext
 */
package php.ware;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.scoping.IScopeProvider;

import php.ware.scoping.ConfigScopeProvider;
import php.ware.valueconverter.ConfigValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class ConfigRuntimeModule extends php.ware.AbstractConfigRuntimeModule {
    @Override
    public Class<? extends IScopeProvider> bindIScopeProvider() {
        return ConfigScopeProvider.class;
    }

    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return ConfigValueConverterService.class;
    }
}
